### ISSUE TITLE
Install all but error in opensim module

### ISSUE THREAD

**Issue by johnfelipe** [Myopengrid/mwi#20]
Whoops!

Server Error: 500 (Internal Server Error)

What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our home page?

**Comment by JeffCost** [comment]
While setting up OpenSim module, if the robust database credentials (opensim database username, password, etc) are wrong or fail to connect, you will get this error. This is a known bug and probably will be fixed in a future release of mwi. To fix this you will have to manually access your mwi database instance and fix your credentials in the table called "mwi_settings", look for database_host, database_name, database_user and database_password. After changing those, if mwi can establish a successful connection with OpenSim database, the error message should stop.

**Comment by jemarti** [comment]
I am getting the same error, but have verified that mwi is able to read and write to my opensim database: 

Even though I get the error I can create users through mwi, and have confirmed that the new users are able to logon to my OpenSim installation. 

In what I suspect is a related issue, The welcome screen will only work if I set both Grid Status Block > Show Total Regions and Show Total Online Users to No.   If I enable either of these options I get a Server Error: 500 (Internal Server Error) message when I try to view the welcome splash screen. 

I am running mwi on Windows Server 2008 R2, OpenSim 0.8.0.1, PHP 5.3.28, and MySQL 5.6.20

**Comment by Xantis** [comment]
Thats correct it can connect to the Robust database I am also using  Windows Server 2008 R2, OpenSim 0.8.0.1, but PHP 5.4.28, I updated the PHP after i did read something about a issue with  PHP 5.3.28, besides in Random i get this  error :: Server Error: 500 (Internal Server Error) in random, i used this structure  wwwroot---dsg where dsg is  my public folder in this case and all other folders as sun folders  on the dsg folder so  i would type http:\www.dsgrid\dsg\  But whatever i do i can not solve this strange Server Error: 500 (Internal Server Error) behavior, and yes all folders (needed) are on 777.

And  at  last Jeff with all due respect but we know the database structure from Opensim in my case a separated database for  the grid (Robust) and  that lady who said that it was a PHP 5.3.28, issue and with PHP 5.4.28 it would be solved thats also not the case. It does  the same. I think the MWI database should be full compatible with the database from either opensim or Robust if thats the issue, however i did run on a Error: 500 (Internal Server Error) message while i had not even the database configured for opensim, i did click on opensim and got that error twice then it was gone, this is something else though. As for a test i used another PHP base web interface and  there was no error at all. Anyway its about MWI.

**Comment by JeffCost** [comment]
I will take a look in this issue when i get a free time, as soon as possible.

**Comment by CaptMetatron** [comment]
I can narrow this down way further, I think.
Unhandled Exception

Message:

Trying to get property of non-object
Location:

C:\AMG\mg\bundles\pages\libraries\Restriction.php on line 20
Stack Trace:

#0 C:\AMG\mg\laravel\laravel.php(42): Laravel\Error::native(8, 'Trying to get p...', 'C:\AMG\mg\bundl...', 20)
#1 C:\AMG\mg\bundles\pages\libraries\Restriction.php(20): Laravel{closure}(8, 'Trying to get p...', 'C:\AMG\mg\bundl...', 20, Array)
#2 C:\AMG\mg\bundles\pages\libraries\Page.php(68): Pages\Restriction::passes(Array, Object(Laravel\Auth))
#3 C:\AMG\mg\bundles\pages\controllers\frontend\pages.php(13): Pages\Page->render()
#4 [internal function]: Pages_Frontend_Pages_Controller->get_index('home')
#5 C:\AMG\mg\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#6 C:\AMG\mg\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('index', Array)
#7 C:\AMG\mg\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('index', Array)
#8 C:\AMG\mg\bundles\pages\routes.php(7): Laravel\Routing\Controller::call('pages::frontend...', Array)
#9 [internal function]: {closure}('home')
#10 C:\AMG\mg\laravel\routing\route.php(163): call_user_func_array(Object(Closure), Array)
#11 C:\AMG\mg\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#12 C:\AMG\mg\laravel\laravel.php(167): Laravel\Routing\Route->call()
#13 C:\AMG\mg\www\index.php(39): require('C:\AMG\mg\larav...')
#14 {main}

C:\AMG\mg\bundles\pages\libraries\Restriction.php on line 20 reads:

```
    if(isset($user) and ($user->id == 1 or $user->group->slug == 'admin'))
```

What SHOULD it read? everything below this in the file shows up as not working in Notepad++, (which is a lot smarter than I am) Is there a way to set it so that the users are just automatically given 'user' status? I don't need to ad or remove any more admins, and if I do, I can always do it in the users module manually...

**Comment by CaptMetatron** [comment]
SHOULD it read?

**Comment by animalillo** [comment]
i'm also getting this error, i've enabled error display and this is looking for an unexisting table, i have opensim 0.8.2.1 setup working.

Here is the error message

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'opensim.regions' doesn't exist

SQL: SELECT \* FROM `regions`

Bindings: array (
)

and here goes the stack trace
#0 /var/mwi/laravel/database/connection.php(183): Laravel\Database\Connection->execute('SELECT \* FROM `...', Array)
#1 /var/mwi/laravel/database/query.php(709): Laravel\Database\Connection->query('SELECT * FROM`...', Array)
#2 /var/mwi/laravel/database/eloquent/query.php(90): Laravel\Database\Query->get(Array)
#3 /var/mwi/laravel/database/eloquent/model.php(235): Laravel\Database\Eloquent\Query->get()
#4 /var/mwi/bundles/opensim/helper.php(267): Laravel\Database\Eloquent\Model::all()
#5 [internal function]: Opensim\get_regions()
#6 /var/mwi/application/helpers.php(43): call_user_func('opensim\get_reg...')
#7 [internal function]: Laravel\Bundle::{closure}(Object(Settings\Model\Setting))
#8 /var/mwi/laravel/form.php(612): call_user_func_array(Object(Closure), Array)
#9 [internal function]: Laravel\Form::__callStatic('mwi_field', Array)
#10 [internal function]: Laravel\Form::mwi_field(Object(Settings\Model\Setting))
#11 /var/mwi/laravel/view.php(386) : eval()'d code(16): call_user_func('\Form::mwi_fiel...', Object(Settings\Model\Setting))
#12 /var/mwi/laravel/view.php(386): eval()
#13 /var/mwi/laravel/blade.php(71): Laravel\View->get()
#14 [internal function]: Laravel\Blade::Laravel{closure}(Object(Laravel\View))
#15 /var/mwi/laravel/event.php(199): call_user_func_array(Object(Closure), Array)
#16 /var/mwi/laravel/event.php(138): Laravel\Event::fire('laravel.view.en...', Array, true)
#17 /var/mwi/laravel/view.php(348): Laravel\Event::until('laravel.view.en...', Array)
#18 /var/mwi/laravel/view.php(447): Laravel\View->render()
#19 /var/mwi/laravel/view.php(372): Laravel\View->data()
#20 /var/mwi/laravel/blade.php(71): Laravel\View->get()
#21 [internal function]: Laravel\Blade::Laravel{closure}(Object(Laravel\View))
#22 /var/mwi/laravel/event.php(199): call_user_func_array(Object(Closure), Array)
#23 /var/mwi/laravel/event.php(138): Laravel\Event::fire('laravel.view.en...', Array, true)
#24 /var/mwi/laravel/view.php(348): Laravel\Event::until('laravel.view.en...', Array)
#25 /var/mwi/laravel/view.php(590): Laravel\View->render()
#26 /var/mwi/laravel/response.php(268): Laravel\View->__toString()
#27 /var/mwi/laravel/laravel.php(180): Laravel\Response->render()
#28 /var/mwi/public/index.php(39): require('/var/mwi/larave...')
#29 {main}

Maybe this is because I have different databases for different services?
