### ISSUE TITLE
Install error on step 4 

### ISSUE THREAD

**Issue by edwardantony** [Myopengrid/mwi#24]
can you please help me out the install error on step 4 for the fresh install of latest version

Whoops!
Server Error: 500 (Internal Server Error)
What does this mean?
Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

**Comment by JeffCost** [comment]
You could change the error details to get a better error message by changing the following:
application/config/error.php look for "detail" and change 

``` php
'detail' => false,
```

to

``` php
'detail' => true,
```

This should give you a better error message.

**Comment by edwardantony** [comment]
Error Message

Unhandled Exception

Message:

is_writable(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com:/var/sentora/temp/)
Location:

/var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/email/libraries/swiftmailer/preferences.php on line 15
Stack Trace:

#0 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/laravel.php(42): Laravel\Error::native(2, 'is_writable(): ...', '/var/sentora/ho...', 15)
#1 [internal function]: Laravel{closure}(2, 'is_writable(): ...', '/var/sentora/ho...', 15, Array)
#2 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/email/libraries/swiftmailer/preferences.php(15): is_writable('/tmp')
#3 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/email/libraries/swiftmailer/swift_init.php(28): require('/var/sentora/ho...')
#4 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/email/start.php(29): require('/var/sentora/ho...')
#5 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/bundle.php(102): require('/var/sentora/ho...')
#6 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/registration/tasks/schema.php(10): Laravel\Bundle::start('email')
#7 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/install/libraries/installer.php(803): Registration_Schema_Task->__construct()
#8 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/install/libraries/installer.php(733): Install\Installer::schema('install', 'registration')
#9 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/install/controllers/frontend/install.php(314): Install\Installer::install()
#10 [internal function]: Install_Frontend_Install_Controller->post_step_4(NULL)
#11 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#12 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('step_4', Array)
#13 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('step_4', Array)
#14 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/bundles/install/routes.php(13): Laravel\Routing\Controller::call('install::fronte...', Array)
#15 [internal function]: {closure}('step_4')
#16 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/routing/route.php(163): call_user_func_array(Object(Closure), Array)
#17 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#18 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/laravel/laravel.php(167): Laravel\Routing\Route->call()
#19 /var/sentora/hostdata/zadmin/public_html/virtualworld_live2i_com/public/index.php(39): require('/var/sentora/ho...')
#20 {main}
